python scripts/plot_recon.py \
  --model_path output/simple_rnn/models/baseline_v17_real_final.pt \
  --output_name reconstructions_v17_real_final.png \
  --direction bi \
  --num_examples 3 \
  --seq_length 512 \
  --hidden_size 64 \
  --min_size 5 \
  --max_size 100 \
  --mask_portion 0.3 \
  --random_seed 69 \
  --mode parallel \
  --lags 1 16 64 \
  --use_flow \
  --flow_mode mean  # Options: mode, mean, sample