python scripts/plot_recon.py \
  --model_path output/simple_rnn/models/baseline_v7_100_epochs.pt \
  --output_name reconstructions_v7_100_epochs.png \
  --direction forward \
  --num_examples 3 \
  --seq_length 512 \
  --hidden_size 64 \
  --min_size 2 \
  --max_size 40 \
  --mask_portion 0.0 \
  --random_seed 19 \
  --mock_sinusoid \
  --lags 1 8 32 64