python src/lcgen/train_simple_rnn.py \
  --input data/timeseries.h5 \
  --random_seed 19 \
  --direction forward \
  --max_length 512 \
  --num_samples 2048 \
  --output_name baseline_v3_parallel.pt \
  --epochs 100 \
  --lr 1e-3 \
  --min_size 2 \
  --max_size 40 \
  --mask_portion 0.0 \
  --mock_sinusoid \
  --K 64